apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: calyptia-fluentd
  namespace: kube-system
  labels:
    k8s-app: calyptia-fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: calyptia-fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: calyptia-fluentd-logging
        version: v1
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: calyptia-fluentd
        image: ghcr.io/calyptia/calyptia-fluentd-kubernetes-daemonset:v1-debian-opensearch
        env:
          - name:  FLUENT_OPENSEARCH_HOST
            value: "opensearch-logging"
          - name:  FLUENT_OPENSEARCH_PORT
            value: "9200"
          - name: FLUENT_OPENSEARCH_SCHEME
            value: "http"
          # Option to configure OpenSearch plugin with self signed certs
          # ================================================================
          - name: FLUENT_OPENSEARCH_SSL_VERIFY
            value: "true"
          # Option to configure OpenSearch plugin with tls
          # ================================================================
          - name: FLUENT_OPENSEARCH_SSL_VERSION
            value: "TLSv1_2"
          # X-Pack Authentication
          # =====================
          - name: FLUENT_OPENSEARCH_USER
            value: "elastic"
          - name: FLUENT_OPENSEARCH_PASSWORD
            value: "changeme"
          # - name: FLUENTD_SYSTEMD_CONF
          #   value: "disable"
          # - name: FLUENTD_AWS_OPENSEARTCH_SERVICE_CREDENTAILS_CONF
          #   value: "disable"
          # Calyptia Authentication
          # ======================
          - name: FLUENT_CALYPTIA_MONITORING_CALYPTIA_API_KEY
            value: "YOUR_API_KEY"
          # Logz.io Authentication
          # ======================
          - name: LOGZIO_TOKEN
            value: "ThisIsASuperLongToken"
          - name: LOGZIO_LOGTYPE
            value: "kubernetes"
          - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
            value: "cri"
          - name: FLUENT_CONTAINER_TAIL_PARSER_TIME_FORMAT
            value: "%Y-%m-%dT%H:%M:%S.%L%z"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: dockercontainerlogdirectory
          mountPath: /var/log/pods
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: dockercontainerlogdirectory
        hostPath:
          path: /var/log/pods
