name: Docker image building
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: v1.15/debian-elasticsearch7
          - dockerfile: v1.15/debian-elasticsearch8
          - dockerfile: v1.15/debian-forward
          - dockerfile: v1.15/debian-kafka2
          - dockerfile: v1.15/debian-opensearch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: make image DOCKERFILE=${{ matrix.dockerfile }} VERSION=test
