name: Docker image publishing
on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]
jobs:
  publish-image:
    name: Publish docker image
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: v1.15/debian-elasticsearch7
          - dockerfile: v1.15/debian-elasticsearch8
          - dockerfile: v1.15/debian-forward
          - dockerfile: v1.15/debian-kafka2
          - dockerfile: v1.15/debian-opensearch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Login to GitHub Container Registry
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        run: |
          make multiarch-image DOCKERFILE=${{ matrix.dockerfile }}
          make multiarch-tags DOCKERFILE=${{ matrix.dockerfile }}
      - name: Push image tags
        if: startsWith(github.ref, 'refs/tags/v')
        run: make multiarch-push DOCKERFILE=${{ matrix.dockerfile }}
