name: Docker image publishing
on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]
jobs:
  publish-image:
    name: Publish docker image
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: v1.14/debian-elasticsearch7
          - dockerfile: v1.14/debian-forward
          - dockerfile: v1.14/debian-kafka2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Login to GitHub Container Registry
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          make image DOCKERFILE=${{ matrix.dockerfile }}
          make tags DOCKERFILE=${{ matrix.dockerfile }}
      - name: Push image tags
        if: startsWith(github.ref, 'refs/tags/v')
        run: make push DOCKERFILE=${{ matrix.dockerfile }}
